### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rumi55** [tom-it/3rdlevelcategory-opencart#1]
Hello,

This is not working on oc3!

**Comment by tom-it** [comment]
Did you refresh the modification? and cache?

**Comment by rumi55** [comment]
Yes and yes.

**Comment by tom-it** [comment]
I need more info, it works on OC3 I’m using it too. Any error messages? Custom theme?

**Comment by rumi55** [comment]
Im running it on localhost and I switched to default theme. So, I dont get it. No error on error logs.
